version: "3.7"

services:
    app:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - postgres

    postgres:
        image: postgres:latest
        environment:
            POSTGRES_USER: dev
            POSTGRES_PASSWORD: "@lockDev"
            POSTGRES_DB: map
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
        driver: local
